name: Generate and Deploy JavaDoc

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build project and download all dependencies
        run: mvn clean install -DskipTests


      - name: Prepare lib directory with JavaFX and Jackson
        run: |
          mkdir -p lib
          mvn dependency:copy-dependencies -DincludeScope=compile -DoutputDirectory=lib
          find ~/.m2/repository/org/openjfx -name "*.jar" -exec cp {} lib/ \;
          find ~/.m2/repository/com/fasterxml/jackson/core -name "*.jar" -exec cp {} lib/ \;

      - name: Generate Javadocs (module-path aware)
        run: |
          mkdir -p javadocs
          javadoc \
            --module-path lib \
            --add-modules javafx.controls,javafx.fxml \
            -d javadocs \
            -sourcepath src/main/java \
            -subpackages edu.cairn.cis332finalproject

      - name: Deploy JavaDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./javadocs
