name: Generate and Deploy JavaDoc

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Download JavaFX and Jackson
        run: |
          mkdir -p lib
          wget https://download2.gluonhq.com/openjfx/24/openjfx-24.0.1_linux-x64_bin-sdk.zip
          unzip openjfx-24.0.1_linux-x64_bin-sdk.zip -d $HOME/javafx
          
          wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.18.3/jackson-core-2.18.3.jar -P lib
          wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.18.3/jackson-databind-2.18.3.jar -P lib
          wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.18.3/jackson-annotations-2.18.3.jar -P lib

      - name: Generate JavaDoc
        run: |
          mkdir -p javadocs
          javadoc \
            -d javadocs \
            --module-path "$HOME/javafx/javafx-sdk-24.0.1/lib:lib" \
            --add-modules javafx.controls,javafx.fxml \
            -sourcepath src/main/java \
            -subpackages edu.cairn.cis332finalproject

      - name: Deploy JavaDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./javadocs
