name: Generate and Deploy JavaDoc

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Build project and download all dependencies
        run: mvn clean install -DskipTests


      - name: Copy JavaFX and Jackson to lib/
        run: |
          mkdir -p lib
          cp ~/.m2/repository/org/openjfx/javafx-controls/24.0.1/javafx-controls-24.0.1.jar lib/
          cp ~/.m2/repository/org/openjfx/javafx-fxml/24.0.1/javafx-fxml-24.0.1.jar lib/

          cp ~/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.15.3/jackson-core-2.15.3.jar lib/
          cp ~/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.15.3/jackson-databind-2.15.3.jar lib/
          cp ~/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.15.3/jackson-annotations-2.15.3.jar lib/
      

      - name: Generate JavaDoc
        run: |
          mkdir -p javadocs
          javadoc \
            -d javadocs \
            --module-path "$HOME/javafx/javafx-sdk-24.0.1/lib:lib" \
            --add-modules javafx.controls,javafx.fxml \
            -sourcepath src/main/java \
            -subpackages edu.cairn.cis332finalproject

      - name: Deploy JavaDoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./javadocs
