name: Generate JavaDoc

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Install JavaFX (Linux only)
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget
          wget https://download2.gluonhq.com/openjfx/20/openjfx-20_linux-x64_bin-sdk.zip
          unzip openjfx-20_linux-x64_bin-sdk.zip -d $HOME/javafx
        shell: bash

      - name: Download Jackson Dependencies
        run: |
          mkdir -p lib
          wget https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.15.3/jackson-core-2.15.3.jar -P lib
          wget https://repo1.maven.org/maven2/com/fasterxml/jackson/databind/jackson-databind/2.15.3/jackson-databind-2.15.3.jar -P lib
          wget https://repo1.maven.org/maven2/com/fasterxml/jackson/annotations/jackson-annotations/2.15.3/jackson-annotations-2.15.3.jar -P lib

      - name: Generate JavaDoc
        run: |
          mkdir -p javadocs
          javadoc \
            -d javadocs \
            --module-path "$HOME/javafx/javafx-sdk-20/lib:lib" \
            --add-modules javafx.controls,javafx.fxml \
            -sourcepath src/main/java \
            -subpackages edu.cairn.cis332finalproject
        shell: bash

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./javadocs
